# Generated by Django 4.0.1 on 2022-01-16 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('sheet_name', models.CharField(max_length=255)),
                ('upload_type', models.IntegerField(choices=[[0, 'ZERODHA'], [1, 'ANGEL'], [2, 'UPSTOX'], [3, 'OTHERS']], default=3)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.IntegerField(choices=[[0, 'NSE'], [1, 'BSE']])),
                ('time', models.DateTimeField()),
                ('trade_type', models.IntegerField(choices=[[0, 'BUY'], [1, 'SELL']])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exec_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader', to=settings.AUTH_USER_MODEL)),
                ('related_trade_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet', to='trade.tradesheet')),
                ('trade_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.tradeitem')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField()),
                ('contained_items', models.ManyToManyField(to='trade.TradeItem')),
                ('related_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-status_date',),
            },
        ),
    ]
