# Generated by Django 4.0.1 on 2022-01-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_symbol', models.CharField(max_length=8)),
                ('trade_in', models.DateTimeField()),
                ('trade_out', models.DateTimeField()),
                ('exec_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader', to='trader.trader')),
            ],
        ),
    ]
