# Generated by Django 4.0.1 on 2022-01-12 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('sheet_name', models.CharField(max_length=255)),
                ('upload_type', models.IntegerField(choices=[[0, 'ZERODHA'], [1, 'ANGEL'], [2, 'UPSTOX'], [3, 'OTHERS']], default=3)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_symbol', models.CharField(max_length=8)),
                ('trade_in', models.DateTimeField()),
                ('trade_out', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exec_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader', to=settings.AUTH_USER_MODEL)),
                ('related_trade_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet', to='trade.tradesheet')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
