version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: tradeuser
      POSTGRES_DB: tradeapp
      POSTGRES_PASS: user@trader12
    volumes:
      - pgdata:/var/lib/postgresql/data
  tradeapp:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/tradeapp
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: