# Generated by Django 4.0.1 on 2022-01-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliostatus',
            name='contained_items',
        ),
        migrations.AddField(
            model_name='portfoliostatus',
            name='contained_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.tradeitem'),
        ),
        migrations.AddField(
            model_name='portfoliostatus',
            name='exit_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliostatus',
            name='net_profit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliostatus',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
