# Generated by Django 4.0.3 on 2022-03-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_remove_portfoliostatus_contained_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_type', models.IntegerField(choices=[[0, 'SUPPORT'], [1, 'RESISTANCE']])),
                ('mark_start', models.DateField()),
                ('mark_end', models.DateField()),
                ('mark_value', models.FloatField()),
                ('index_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.indexsymbol')),
            ],
        ),
    ]
