# Generated by Django 4.0.1 on 2022-01-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('trade_in', models.DateTimeField()),
                ('trade_out', models.DateTimeField()),
                ('trade_symbol', models.CharField(max_length=63)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.trader')),
            ],
        ),
    ]
